[package]
name = "dynamic_module_segfault"
version = "0.1.0"
authors = ["Jack May <jack@solana.com>"]

[dependencies]
libc = "0.2.43"
libloading = "0.5.0"

[workspace]
members = [
    ".",
    "dylibs/noop",
]
default-members = [
    ".",
    "dylibs/noop",
]
